### ISSUE TITLE
Enable Stacktraces for Unit Tests 

### ISSUE THREAD

**Issue by chenhao94** [cyfitech/cris-core#104]

**Comment by YuzhouGuo** [comment]
Since currently, unit tests did tell you which line of the source code the exception came from. I suppose this stack trace enabling feature is something similar to what we did in `cris` before, meaning signal capture and boost stacktrace printing, so no need to touch the `gtest` framework? @chenhao94 @xkszltl

**Comment by YuzhouGuo** [comment]
@chenhao94 All repos should updated to `cris_gtest_main` as the bazel build option, this issue has been resolved.
